name: Build And Releas

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Test echo RELEASE_VERSION
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}

    - name: Get dependencies and build
      run: |
        yarn install
        yarn build

    - name: Package
      run: tar -zcvf subweb-${{ env.RELEASE_VERSION }}.tar.gz dist

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        
    - name: Upload files to GH release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        tag: ${{ github.ref }}
        file: subweb-${{ env.RELEASE_VERSION }}.tar.gz
        asset_name: subweb-${{ env.RELEASE_VERSION }}.tar.gz
        prerelease: true
